name: Sync README fragments
on: workflow_dispatch
permissions:
  contents: write
jobs:
  sync-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          path: main
          fetch-depth: 2
      - name: Checkout upstream
        uses: actions/checkout@v4
        with:
          repository: octogonz-dev-test/md-sync-upstream
          path: md-sync-upstream
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Run script
        run: node main/scripts/sync-readme.js --commit
        